"""Hardcoded OneData defaults for SoMES UC3.3 ops (SCDI space)."""

DEFAULT_ONEZONE_HOST = "data.spice-platform.eu"
DEFAULT_INPUT_DIR = "onedata:///SCDI/UC3.3_SOMES/inputs"
DEFAULT_OUTPUT_DIR = "onedata:///SCDI/UC3.3_SOMES/outputs"
DEFAULT_ONEDATA_TOKEN = (
    "MDAyNGxvY2F00aW9uIGRhdGEuc3BpY2UtcGxhdGZvcm00uZXUKMDA2YmlkZW500aWZpZXIgMi9ubWQvdXNyLWMzZjNkNDc3NjE3MzBiMjk4OWZkNzEyZTJmODc4YWJiY2hlMTdiL2FjdC8yODNjMzExMmU1NmVhNjgxMWUxOGUyYWRkZTdiYjJjNGNoOGNjZgowMDJmc2lnbmF00dXJlIL1Iu96JPccUim5K102wEE01WY00yzaw3E5uAt88MXsxl02pCg"
)
